### ISSUE TITLE
Where to use mixpanel.init

### ISSUE THREAD

**Issue by samuelcastro** [mixpanel/mixpanel-js#140] opened 2017-09-11 16:06 UTC
Should I use `mixpanel.init("YOUR_TOKEN");` in all files I'll use mixpanel or just once?

**Comment by saadaouad** [comment] 2017-11-08 02:11
Maybe in all files that you should use Mixpanel, and i think it's not useful!

**Comment by tdumitrescu** [comment] 2017-11-08 02:25
No, you only need to init once.

If you're using the standard global-var installation, you can reference `mixpanel` anywhere after the embed code has run and it will work.

If you're using a modularized build, you can pass around the initialized `mixpanel` instance. A common pattern is to have one module initialize the lib with your token and config, and then export the initialized instance. E.g.,

`my-mixpanel-instance.js`
```js
import mixpanelLib from 'mixpanel-browser';

export const mixpanel = mixpanelLib.init(token, config);
```

`my-sweet-app.js`
```js
import {mixpanel} from './my-mixpanel-instance';

mixpanel.track(/* ... */);
```

`another-module-in-the-same-app.js`
```js
import {mixpanel} from './my-mixpanel-instance';

mixpanel.track(/* ... */);
```

**Comment by tdumitrescu** [comment] 2017-11-08 02:26
PS for personalized support on usage questions like this, you'll get a quick and helpful response by writing in to support@mixpanel.com.

**Comment by conatus** [comment] 2017-11-08 16:00
Hey @tdumitrescu - I'm afraid the above example doesn't work.

Digging into it but it is because calling `mixpanel.init` returns `undefined` when this code assumes it returns a function or instance of itself.

**Comment by tdumitrescu** [comment] 2017-11-08 16:37
Yes @conatus AFAIK the only way `mixpanel.init` should return `undefined` is either:
- it threw an error before reaching https://github.com/mixpanel/mixpanel-js/blob/8b2e1f7b0e066482836e2c5484558e3c356d492a/src/mixpanel-core.js#L775. In this case the instance wouldn't have been usable anyway.
- you're using the global embed-code script tag which has its own version of `init` that runs before the library is loaded: https://github.com/mixpanel/mixpanel-js/blob/8b2e1f7b0e066482836e2c5484558e3c356d492a/mixpanel-jslib-snippet.js#L36. This initializes a global `mixpanel` variable which you can use anywhere, in which case you don't even need to pass it around (or import the mixpanel CJS module at all). But if you wanted to abstract its globalness away from other modules you could export the `window.mixpanel` object for others to consume.

**Comment by conatus** [comment] 2017-11-08 17:07
Thanks for that.

I wasn't using the embed code deliberately so suspect there is some kind of collision here as a result of Mixpanel being accidentally loaded twice. Google Tag Manager is on the page as well, possibly implementing its own Mixpanel...

**Comment by bjunc** [comment] 2018-01-22 21:59
I'm actually having an issue with `mixpanel.init` returning `undefined` as well:

```js
import mixpanelLib from 'mixpanel-browser';
const mixpanel = mixpanelLib.init("ABC123")
console.log(mixpanel) // undefined
```

Is there a way to debug this?  FYI, I'm not using the global mixpanel embed code.

**Comment by tdumitrescu** [comment] 2018-01-23 02:02
@bjunc I think you're best off contacting support@mixpanel.com so that we can look at your specific setup. It seems like you'd have to be hitting one of these error conditions: https://github.com/mixpanel/mixpanel-js/blob/8b2e1f7b0e066482836e2c5484558e3c356d492a/src/mixpanel-core.js#L762-L769

**Comment by chulander** [comment] 2018-02-06 18:57
I'm receiving the same error output yet mixpanel is confirmed to be actively tracking without issues. Any thoughts @tdumitrescu?

```javascript
Mixpanel error: "mixpanel" object not initialized. Ensure you are using the latest version of the Mixpanel JS Library along with the snippet we provide.
```

**Comment by tdumitrescu** [comment] 2018-02-06 19:47
@chulander We've received a few similar reports starting this morning and are investigating. If you could write in to support@mixpanel.com with info about your OS, browser+version, and any installed browser extensions that would be a big help in tracking down the issue. Thanks!

**Comment by tdumitrescu** [comment] 2018-02-06 20:06
@chulander do you happen to use the Page Ruler extension for Chrome? They shipped an update todayish that adds a conflicting top-level `mixpanel` object, and are in the process of updating to disable it. https://chrome.google.com/webstore/detail/page-ruler/jlpkojjdgbllmedoapgfodplfhcbnbpn/reviews?hl=en

**Comment by chulander** [comment] 2018-02-07 16:47
hi @tdumitrescu. I do have the page ruler extensions and once disabled, the error no longer appears. Apologies, I should have tried incognito mode first before adding to this issue tracker. Thanks for the prompt reply!

**Comment by tdumitrescu** [comment] 2018-02-07 17:06
Glad to help. I'm going to close this issue out for now. If anyone has relevant questions that aren't answered above, feel free to reopen, or write in to support@mixpanel.com if you'd like to discuss the details of your specific implementation with someone smart!

**Closed by tdumitrescu** 2018-02-07 17:06 UTC
