### ISSUE TITLE
`mixpanel.track` mutates attributes

### ISSUE THREAD

**Issue by trotzig** [mixpanel/mixpanel-js#113] opened 2016-12-05 12:34 UTC
You can decide whether or not you consider this a bug, but I thought I'd at least post it here. 

We have some code that calls `mixpanel.track` with a second argument (event attributes). After this call, the attributes have been mutated. 

```
const attrs = { foo: 1 };
mixpanel.track('some-event', attrs);
console.log(attrs);
// => {foo: 1, token: "6f39bdxyxy2345xyzyxf341a058dd2ce5e87f"}
```

This came as a gotcha to me, and I think it would be better if you left the attributes alone.

**Comment by tdumitrescu** [comment] 2016-12-05 17:42
Duplicate of https://github.com/mixpanel/mixpanel-js/issues/107, please add any discussion there, thanks.

**Closed by tdumitrescu** 2016-12-05 17:42 UTC
