### ISSUE TITLE
Loading a specific version from the CDN

### ISSUE THREAD

**Issue by rmacklin** [mixpanel/mixpanel-js#165] opened 2018-02-01 20:23 UTC
Hi. I need to downgrade MixPanel because the latest version released this morning (v2.16.0) broke an application I work on.

We're currently pulling in the "latest" version via `https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js`.

I'd like to revert to the previous version, v2.15.0. I thought that `https://cdn.mxpnl.com/libs/mixpanel-2.15.min.js` or `https://cdn.mxpnl.com/libs/mixpanel-2.15.0.min.js` would work, but it doesn't. I can successfully access `https://cdn.mxpnl.com/libs/mixpanel-2.3.min.js` (which is a three year old version) but no higher versions -- perhaps you changed your URLs and I'm just not trying the correct format.

Are specific versions of the library after v2.3 still available on the CDN?

**Comment by evnp** [comment] 2018-02-01 22:53
Hey, really sorry to hear our release caused an issue. Would you be willing to send error details to support@mixpanel.com? Then we can repro and fix the problem. We'll also help load an earlier version of the lib if necessary. Thanks

**Comment by rmacklin** [comment] 2018-02-02 00:52
@evnp Thanks for your response.

I did open a support ticket in addition to opening this issue, but I haven't heard back.

As for the error details - it's complicated. So far I've actually only reproduced the issue on our production site - not locally or on our staging environment. There are a few different forms on our site that it broke. In some cases, we were seeing an `<input>` element get replaced with a text node whose value was `/[^a-zA-Z0-9]/`, which is the regular expression from this line of autotrack.js:
https://github.com/mixpanel/mixpanel-js/blob/79bb98da2c85ac632ff328eef4bf107f211527ce/src/autotrack.js#L184

The `name` variable was holding the `input` DOM node, not a string of it's `name` or `id`, so instead of doing a string `replace`, it was overwriting the DOM node. I haven't had much time to dig into the actual javascript execution further.

I don't think mixpanel's javascript on its own is the culprit, but rather it's probably due to the interaction between mixpanel v2.16.0 and other javascript on the page. This is an old application and it has accumulated a lot of third-party javascript, some of which is for our marketing team rather than engineering, which is likely why other environments can't reproduce the issue. But I'm confident that mixpanel's JS client at v2.16.0 is partly responsible, for the following reasons:

1. We only started seeing the issue after the new release was pushed today.
2. The latest release does include changes to autotrack.js that are not far from the line I linked above: https://github.com/mixpanel/mixpanel-js/compare/v2.15.0...v2.16.0?w=1#diff-5328f5c4505ca0b5bf48cff18d6c85a8
3. By blacklisting the mixpanel library in my browser, I stopped seeing the error on our production site. (And unblocking it would immediately result in the issue returning.)
4. I downloaded the v2.15.0 minified file from this repo (https://raw.githubusercontent.com/mixpanel/mixpanel-js/v2.15.0/mixpanel.min.js) and switched to serving that out of our servers instead of using `https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js`. After deploying that change, things started working again.

I'm not able to dig into this issue more today (especially since I was able to ship a fix). I do have a couple of questions though:

1. Is it correct to assume that you no longer serve specific versions from your CDN?
2. Do you have plans to stop supporting v2.15.0 of the javascript client any time soon?

**Comment by ntocampos** [comment] 2018-02-02 13:12
I had the same problem in my project and I have spent some time debugging it.

As on @rmacklin report, the error is being caused by the same line of code:
https://github.com/mixpanel/mixpanel-js/blob/98a1845c5c55f8b362847517860cc97c35f1c08e/src/autotrack.js#L184
In my case, it happens because a `<form>` DOM element is being passed to the `_includeField()` method as an input.

Turns out that when you access some attribute via `.` accessor on a form element, it actually retrieves the input on the form that has the same name as the attribute. 
For instance, if I run `someFormDOMElement.firstname`, it will retrieve the input with name equals to `firstname` if it exists.

So, if I have the variable `input` equals to a form DOM element and I have an input in that form with a name equals "name", the line 
https://github.com/mixpanel/mixpanel-js/blob/98a1845c5c55f8b362847517860cc97c35f1c08e/src/autotrack.js#L182
is actually assigning that input DOM element to the variable `name`. And when the line
https://github.com/mixpanel/mixpanel-js/blob/98a1845c5c55f8b362847517860cc97c35f1c08e/src/autotrack.js#L184
it breaks since the `name` variable isn't a string and don't have a `replace` method.

This bug happens due to [this commit](https://github.com/mixpanel/mixpanel-js/commit/98a1845c5c55f8b362847517860cc97c35f1c08e#diff-5328f5c4505ca0b5bf48cff18d6c85a8). Before it, only `input`, `select` and `textarea` where passed to the old `_includeProperty` method.

There is any way I could lock onto a previous CDN lib version, at least while this isn't fixed?

**Comment by evnp** [comment] 2018-02-02 15:23
Hey @ntocampos @rmacklin, thanks for the detailed investigation and reports. We're working on pushing a fix for this, will be out asap.

**Comment by evnp** [comment] 2018-02-02 17:26
Sorry about the delay. https://github.com/mixpanel/mixpanel-js/releases/tag/v2.17.0 has been pushed with a fix for the issue here: https://github.com/mixpanel/mixpanel-js/commit/ab2862760acaabc93ec62c708d32fd7601f30db4 - this new version is accessible at https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js. If you'd like to pin a specific version the recommended path is to download via npm: https://www.npmjs.com/package/mixpanel-browser. Thanks again for your help resolving this.

**Comment by ntocampos** [comment] 2018-02-05 20:41
Thank you for the availability and readiness.

**Closed** 2018-02-07 19:13 UTC
