### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by arthabus** [mixpanel/mixpanel-js#335] opened 2022-09-09 08:55 UTC
I've just started to get the below error:

```
BaseAnalyticsManager.js:95 RangeError: Maximum call stack size exceeded
    at eval (mixpanel.cjs.js:380:29)
    at Array.forEach (<anonymous>)
    at _.each (mixpanel.cjs.js:165:13)
    at _.truncate (mixpanel.cjs.js:380:11)
    at eval (mixpanel.cjs.js:386:26)
    at _.each (mixpanel.cjs.js:175:30)
    at _.truncate (mixpanel.cjs.js:385:11)
    at eval (mixpanel.cjs.js:386:26)
    at _.each (mixpanel.cjs.js:175:30)
    at _.truncate (mixpanel.cjs.js:385:11)
```

Environment:
"mixpanel-browser": "^2.45.0"
chrome Version 104.0.5112.101 (Official Build) (x86_64)
MacOs 12.0.1 (21A559)

Any suggestions?

**Comment by tdumitrescu** [comment] 2022-09-12 23:55
Looks like a duplicate of https://github.com/mixpanel/mixpanel-js/issues/318. One of my comments there mentions the typical cause: "This infinite recursion issue happens when you pass an Object to `track()` that has a circular reference to itself somewhere"

If you want to discuss further, please use the other issue, thanks.

**Closed by tdumitrescu** 2022-09-12 23:55 UTC
